name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test building
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [5.0.100]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run build
